// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventAPI.proto

package EventClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventObj struct {
	// unique ID for client
	ClientID string `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	// to specify what type of event they are sending
	EventID string `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	// time value
	TimeSinceEpoch *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timeSinceEpoch,proto3" json:"timeSinceEpoch,omitempty"`
	// all data and any other sort of tags
	DataSet              map[string]string `protobuf:"bytes,3,rep,name=dataSet,proto3" json:"dataSet,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventObj) Reset()         { *m = EventObj{} }
func (m *EventObj) String() string { return proto.CompactTextString(m) }
func (*EventObj) ProtoMessage()    {}
func (*EventObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_EventClient_ded7f0a86c3c4b42, []int{0}
}
func (m *EventObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventObj.Unmarshal(m, b)
}
func (m *EventObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventObj.Marshal(b, m, deterministic)
}
func (dst *EventObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventObj.Merge(dst, src)
}
func (m *EventObj) XXX_Size() int {
	return xxx_messageInfo_EventObj.Size(m)
}
func (m *EventObj) XXX_DiscardUnknown() {
	xxx_messageInfo_EventObj.DiscardUnknown(m)
}

var xxx_messageInfo_EventObj proto.InternalMessageInfo

func (m *EventObj) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *EventObj) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *EventObj) GetTimeSinceEpoch() *timestamp.Timestamp {
	if m != nil {
		return m.TimeSinceEpoch
	}
	return nil
}

func (m *EventObj) GetKeyValues() map[string]string {
	if m != nil {
		return m.KeyValues
	}
	return nil
}

type EventResp struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResp) Reset()         { *m = EventResp{} }
func (m *EventResp) String() string { return proto.CompactTextString(m) }
func (*EventResp) ProtoMessage()    {}
func (*EventResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_EventClient_ded7f0a86c3c4b42, []int{1}
}
func (m *EventResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResp.Unmarshal(m, b)
}
func (m *EventResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResp.Marshal(b, m, deterministic)
}
func (dst *EventResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResp.Merge(dst, src)
}
func (m *EventResp) XXX_Size() int {
	return xxx_messageInfo_EventResp.Size(m)
}
func (m *EventResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResp.DiscardUnknown(m)
}

var xxx_messageInfo_EventResp proto.InternalMessageInfo

func (m *EventResp) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*EventObj)(nil), "EventClient.EventObj")
	proto.RegisterMapType((map[string]string)(nil), "EventClient.EventObj.DataSetEntry")
	proto.RegisterType((*EventResp)(nil), "EventClient.EventResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventSenderClient is the client API for EventSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventSenderClient interface {
	// Sends the event and does not get anything back
	SendEvent(ctx context.Context, in *EventObj, opts ...grpc.CallOption) (*EventResp, error)
}

type eventSenderClient struct {
	cc *grpc.ClientConn
}

func NewEventSenderClient(cc *grpc.ClientConn) EventSenderClient {
	return &eventSenderClient{cc}
}

func (c *eventSenderClient) SendEvent(ctx context.Context, in *EventObj, opts ...grpc.CallOption) (*EventResp, error) {
	out := new(EventResp)
	err := c.cc.Invoke(ctx, "/EventClient.EventSender/SendEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventSenderServer is the server API for EventSender service.
type EventSenderServer interface {
	// Sends the event and does not get anything back
	SendEvent(context.Context, *EventObj) (*EventResp, error)
}

func RegisterEventSenderServer(s *grpc.Server, srv EventSenderServer) {
	s.RegisterService(&_EventSender_serviceDesc, srv)
}

func _EventSender_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventObj)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSenderServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EventClient.EventSender/SendEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSenderServer).SendEvent(ctx, req.(*EventObj))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventSender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EventClient.EventSender",
	HandlerType: (*EventSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventSender_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EventClient.proto",
}

func init() { proto.RegisterFile("EventClient.proto", fileDescriptor_EventClient_ded7f0a86c3c4b42) }

var fileDescriptor_EventClient_ded7f0a86c3c4b42 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x8d, 0x1f, 0xcd, 0x0b, 0x14, 0x5d, 0x54, 0x42, 0x2e, 0x86, 0x20, 0x98, 0xd3, 0x16,
	0xe2, 0x45, 0xa4, 0xa7, 0x6a, 0x0e, 0xd2, 0x83, 0x90, 0x8a, 0xf7, 0x26, 0x3e, 0x6b, 0x6c, 0xba,
	0x1b, 0xb2, 0xdb, 0x40, 0xfe, 0x80, 0xbf, 0x5b, 0x76, 0xb7, 0xab, 0xf5, 0xe3, 0xb6, 0xf3, 0xe6,
	0xcd, 0xce, 0x9b, 0x81, 0x93, 0xac, 0x43, 0x26, 0xef, 0xea, 0x0a, 0x99, 0xa4, 0x4d, 0xcb, 0x25,
	0x27, 0xfe, 0xce, 0x28, 0xbc, 0x58, 0x72, 0xbe, 0xac, 0x71, 0xac, 0xa9, 0x62, 0xf3, 0x3a, 0x96,
	0xd5, 0x1a, 0x85, 0x5c, 0xac, 0x1b, 0xb3, 0x1d, 0x7f, 0x0c, 0x60, 0xa8, 0x05, 0x8f, 0xc5, 0x3b,
	0x09, 0x61, 0x58, 0x6a, 0xdd, 0xc3, 0x7d, 0xe0, 0x44, 0x4e, 0xe2, 0xe5, 0x5f, 0x98, 0x04, 0x70,
	0x84, 0x9d, 0xa1, 0x06, 0x9a, 0xb2, 0x90, 0x4c, 0x61, 0xa4, 0x7e, 0x9d, 0x57, 0xac, 0xc4, 0xac,
	0xe1, 0xe5, 0x5b, 0xe0, 0x46, 0x4e, 0xe2, 0xa7, 0x21, 0x35, 0xe6, 0xd4, 0x9a, 0xd3, 0x27, 0x6b,
	0x9e, 0xff, 0x52, 0x90, 0x29, 0x78, 0x2b, 0xec, 0x9f, 0x17, 0xf5, 0x06, 0x45, 0xb0, 0x1f, 0xb9,
	0x89, 0x9f, 0x5e, 0xd2, 0xdd, 0x6c, 0xf6, 0x46, 0x3a, 0xb3, 0x6b, 0x19, 0x93, 0x6d, 0x9f, 0x7f,
	0xcb, 0xc2, 0x09, 0x8c, 0x7e, 0x92, 0xe4, 0x18, 0xdc, 0x15, 0xf6, 0xdb, 0x28, 0xea, 0x49, 0x4e,
	0xe1, 0xa0, 0x53, 0x0b, 0xdb, 0x0c, 0x06, 0xdc, 0x0e, 0x6e, 0x9c, 0xf8, 0x0a, 0x3c, 0xed, 0x91,
	0xa3, 0x68, 0x54, 0x11, 0x2d, 0x8a, 0x86, 0x33, 0x81, 0xb6, 0x08, 0x8b, 0xd3, 0x19, 0x98, 0x86,
	0xe7, 0xc8, 0x5e, 0xb0, 0x25, 0x13, 0xf0, 0xd4, 0x4b, 0x8f, 0xc8, 0xd9, 0xbf, 0x37, 0x87, 0xe7,
	0x7f, 0xc7, 0xca, 0x26, 0xde, 0x2b, 0x0e, 0x75, 0x37, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x08, 0xe8, 0xc8, 0x5c, 0xc8, 0x01, 0x00, 0x00,
}
